export const RESIDENCE_HALLS = [
  { value: "Greeley Hall", label: "Greeley Hall", group: "Eleanor Roosevelt" },
  { value: "Keller Hall", label: "Keller Hall", group: "Eleanor Roosevelt" },
  { value: "Stimson Hall", label: "Stimson Hall", group: "Eleanor Roosevelt" },
  { value: "Wagner Hall", label: "Wagner Hall", group: "Eleanor Roosevelt" },
  { value: "Benedict North", label: "Benedict North", group: "H Community" },
  { value: "Benedict South", label: "Benedict South", group: "H Community" },
  { value: "James Hall", label: "James Hall", group: "H Community" },
  { value: "Langmuir Hall", label: "Langmuir Hall", group: "H Community" },
  { value: "Ammann Hall", label: "Ammann Hall", group: "Mendelsohn" },
  { value: "Gray Hall", label: "Gray Hall", group: "Mendelsohn" },
  { value: "Irving Hall", label: "Irving Hall", group: "Mendelsohn" },
  { value: "O'Neill Hall", label: "O'Neill Hall", group: "Mendelsohn" },
  { value: "Baruch Hall", label: "Baruch Hall", group: "Kelly" },
  { value: "Dewey Hall", label: "Dewey Hall", group: "Kelly" },
  { value: "Eisenhower Hall", label: "Eisenhower Hall", group: "Kelly" },
  { value: "Hamilton Hall", label: "Hamilton Hall", group: "Kelly" },
  { value: "Schick Hall", label: "Schick Hall", group: "Kelly" },
  { value: "Cardozo Hall", label: "Cardozo Hall", group: "Roth" },
  { value: "Gershwin Hall", label: "Gershwin Hall", group: "Roth" },
  { value: "Hendrix Hall", label: "Hendrix Hall", group: "Roth" },
  { value: "Mount Hall", label: "Mount Hall", group: "Roth" },
  { value: "Whitman Hall", label: "Whitman Hall", group: "Roth" },
  { value: "Chinn Hall", label: "Chinn Hall", group: "Tabler" },
  { value: "Douglass Hall", label: "Douglass Hall", group: "Tabler" },
  { value: "Dreiser Hall", label: "Dreiser Hall", group: "Tabler" },
  { value: "Hand Hall", label: "Hand Hall", group: "Tabler" },
  { value: "Toscanini Hall", label: "Toscanini Hall", group: "Tabler" },
  { value: "West Apartments", label: "West Apartments", group: "Apartments" },
  { value: "Chapin Apartments", label: "Chapin Apartments", group: "Apartments" },
  { value: "Schomburg Apartments", label: "Schomburg Apartments", group: "Apartments" },
  { value: "Off Campus", label: "Off Campus" },
]
