export const SBU_GREEK_LIFE = [
  'Alpha Kappa Alpha',
  'Alpha Kappa Delta Phi',
  'Alpha Phi Alpha',
  'Alpha Phi Omega',
  'Alpha Sigma Alpha',
  'Delta Sigma Pi',
  'Delta Sigma Theta',
  'Iota Nu Delta',
  'Kappa Alpha Psi',
  'Kappa Kappa Psi',
  'Kappa Phi Lambda',
  'Kappa Sigma',
  'Lambda Phi Epsilon',
  'Lambda Theta Alpha',
  'Lambda Theta Phi',
  'Lambda Upsilon Lambda',
  'MALIK Fraternity',
  'Omega Phi Beta',
  'Omega Psi Phi',
  'Phi Alpha Delta',
  'Phi Beta Sigma',
  'Phi Delta Epsilon',
  'Phi Delta Psi',
  'Pi Delta Psi',
  'Pi Kappa Phi',
  'Pi Lambda Phi',
  'Sigma Beta Rho',
  'Sigma Chi',
  'Sigma Delta Tau',
  'Sigma Gamma Rho',
  'Sigma Iota Alpha',
  'Sigma Iota Sigma',
  'Sigma Psi Zeta',
  'Tau Kappa Epsilon',
  'Theta Phi Alpha',
  'Theta Tau',
  'Zeta Phi Beta',
]

export const SBU_CLUBS = [
  'ACM',
  'Active Minds',
  'Adobe Creatives',
  'Afghan Student Organization',
  'African Students Union',
  'AIAA',
  'AIChE',
  'AI Community',
  'Albanian American Student Organization',
  'American Cancer Society at SBU',
  'American Chemical Society',
  'American Marketing Association',
  'American Red Cross Club',
  'American Sign Language Club',
  'Anime Club',
  'Arabic Language and Culture Club',
  'Archery Club',
  'Art Club',
  'ASCE',
  'ASME',
  'Astronomy Club',
  'Badminton Club',
  'Ballroom Dance Team',
  'Bangladeshi Graduate Students Association',
  'Best Buddies',
  'Biology Society',
  'BMES',
  'Boxing Club',
  'Brazilian Jiu Jitsu',
  'Brook Bhangra',
  'Burmese Student Association',
  'Business Analytics Society',
  'Camp Kesem',
  'Caribbean Student Organization',
  'Cat Network',
  'Ceramics Club',
  'Cheerleading',
  'Chess Club',
  'Chinese Association at Stony Brook',
  'Chinese Christian Fellowship',
  'Chinese Students and Scholars Association',
  'Circle K International',
  'Climbing Club',
  'Club Baseball',
  'Club Swimming',
  'College Democrats',
  'College Republicans',
  'ColorStack',
  'Comic Book Club',
  'Commuter Student Association',
  'Competitive Programming Club',
  'Computing Society',
  'Consulting Club',
  'Crew Club',
  'Cricket Club',
  'Crochet Club',
  'Culinary Club',
  'Cybersecurity Club',
  'Dance Team',
  'Debate Society',
  'Desi Dance Team',
  'DnD and More Club',
  'Dodgeball Club',
  'Engineers Without Borders',
  'Environmental Club',
  'Equestrian Club',
  'Esports Club',
  'Fashion Club',
  'Fencing Club',
  'Field Hockey Club',
  'Figure Skating Club',
  'Filipino Student Organization',
  'Finance Society',
  'Fine Arts Organization',
  'First Generation Students',
  'Foraging and Mycology Society',
  'French Language Club',
  'Future Teachers Association',
  'Game Development Club',
  'Geology Club',
  'Girls Who Code',
  'Golf Club',
  'Gospel Choir',
  'Greek and Cypriot Student Association',
  'Greenhouse Club',
  'Habitat for Humanity',
  'Haitian Student Organization',
  'Handball Club',
  'Health and Nutrition Club',
  'Hindu Students Council',
  'History Club',
  'Ice Hockey Club',
  'IEEE',
  'Indian Classical Music Club',
  'Indian Students Association',
  'InterVarsity Christian Fellowship',
  'Investment Club',
  'Irish American Cultural Association',
  'Islamic Society',
  'Japanese Student Organization',
  'Junoon',
  'KBS Dance Team',
  'Kendo Club',
  'Kickboxing Club',
  'Kidney Crew',
  'Korean Christian Fellowship',
  'Korean Student Association',
  'Mahjong Club',
  'MAPS',
  'Marching Band',
  'Marine Science Club',
  'Martial Arts Club',
  'Math Club',
  "Men's Lacrosse",
  "Men's Rugby",
  "Men's Soccer Club",
  'Mentors in Medicine',
  'Meteorology Club',
  'Minorities in Medicine',
  'Mock Trial',
  'Model United Nations',
  'Muslim Students Association',
  'NAACP at SBU',
  'National Society of Black Engineers',
  'Neuroscience Axis',
  'Origami Club',
  'Pakistani Students Association',
  'Persian Culture Club',
  'Philosophy Club',
  'Photography Club',
  'Pickleball Club',
  'Pilates Club',
  'Polish American Student Association',
  'Pre-Dental Society',
  'Pre-Law Society',
  'Pre-Med Society',
  'Pre-Nursing Society',
  'Pre-Occupational Therapy Society',
  'Pre-Optometry Club',
  'Pre-PA Club',
  'Pre-Physical Therapy Club',
  'Pre-Veterinary Society',
  'Project Sunshine',
  'Quant Club',
  'Quiz Bowl and Trivia Club',
  'Real Estate Club',
  'Residence Hall Association',
  'Robotics Team',
  'Roller Hockey',
  'Running Club',
  'Sailing Club',
  'SASE',
  'SBVAC',
  'SBU Taandava',
  'Science Fiction Forum',
  'Science Olympiad',
  'Seawolves for Israel',
  'SHPE',
  'Sikh Student Association',
  'Ski and Snowboard Club',
  'Smash Bros Club',
  'Society of Women Engineers',
  'Softball Club',
  'Solar Racing',
  'South Asian Student Alliance',
  'Spoken Word Poetry Club',
  'Stony Brook Dance Team',
  'Stony Brook Global Medical Brigades',
  'Stony Brook Hillel',
  'Stony Brook MEDLIFE',
  'Stony Brook Motorsports',
  'Stony Brook Press',
  'Stony Brook Vocalists',
  'Strength Club',
  'Student Nurses Association',
  'Sunrise Movement',
  'Synthetic Biology Society',
  'Table Tennis Club',
  'Taekwondo',
  'Taiwanese Students Association',
  'Tennis Club',
  'TEDx SBU',
  'The Bowling Club',
  'The Statesman',
  'Trading Card Game Club',
  'Turkish-American Student Association',
  'Ukrainian-American Student Association',
  'Ultimate Frisbee',
  'Undergraduate Biochemistry Society',
  'Undergraduate Economics Association',
  'Undergraduate Student Government',
  'UNICEF at SBU',
  'Vietnamese Student Association',
  'Volleyball Club',
  'Web Development Club',
  'West Indian Student Alliance',
  'Women in Business',
  'Women in Computer Science',
  'Women in Healthcare',
  'Women in Physics and Astronomy',
  "Women's Club Basketball",
  "Women's Lacrosse",
  "Women's Rugby",
  "Women's Soccer Club",
  'Wrestling Team',
  'WUSB Radio',
  'Yoga Club',
  'Young Investigators Review',
]
