export const SBU_GREEK_LIFE = [
  'Alpha Kappa Alpha',
  'Alpha Kappa Delta Phi',
  'Alpha Phi Alpha',
  'Alpha Sigma Alpha',
  'Delta Sigma Pi',
  'Delta Sigma Theta',
  'Iota Nu Delta',
  'Kappa Alpha Psi',
  'Kappa Phi Lambda',
  'Kappa Sigma',
  'Lambda Phi Epsilon',
  'Lambda Theta Alpha',
  'Lambda Theta Phi',
  'Lambda Upsilon Lambda',
  'Omega Phi Beta',
  'Omega Psi Phi',
  'Phi Beta Sigma',
  'Phi Delta Epsilon',
  'Phi Delta Psi',
  'Pi Delta Psi',
  'Pi Kappa Phi',
  'Pi Lambda Phi',
  'Sigma Beta Rho',
  'Sigma Chi',
  'Sigma Delta Tau',
  'Sigma Gamma Rho',
  'Sigma Iota Alpha',
  'Sigma Psi Zeta',
  'Tau Kappa Epsilon',
  'Theta Phi Alpha',
  'Theta Tau',
  'Zeta Phi Beta',
]

export const SBU_CLUBS = [
  'African Student Union',
  'AI Community',
  'AIAA',
  'AIChE',
  'American Marketing Association',
  'American Red Cross Club',
  'Archery Club',
  'ASCE',
  'ASME',
  'Badminton Club',
  'BMES',
  'Boxing Club',
  'Camp Kesem',
  'Caribbean Student Organization',
  'Chinese Students and Scholars Association',
  'ColorStack',
  'Crew Club',
  'Equestrian Club',
  'Fencing Club',
  'Finance Society',
  'Ice Hockey Club',
  'IEEE',
  'Investment Club',
  'Korean Student Association',
  'MAPS',
  'Martial Arts Club',
  "Men's Lacrosse",
  "Men's Rugby",
  'Mentors in Medicine',
  'Minorities in Medicine',
  'Muslim Students Association',
  'National Society of Black Engineers',
  'Neuroscience Axis',
  'Pre-Dental Society',
  'Pre-Med Society',
  'Pre-Nursing Society',
  'Pre-PA Club',
  'Project Sunshine',
  'Real Estate Club',
  'Running Club',
  'Sailing Club',
  'SASE',
  'SBVAC',
  'SBU Taandava',
  'SHPE',
  'Society of Women Engineers',
  'South Asian Student Alliance',
  'Stony Brook Computing Society',
  'Stony Brook Dance Team',
  'Stony Brook Global Medical Brigades',
  'Stony Brook Hillel',
  'Stony Brook MEDLIFE',
  'Stony Brook Motorsports',
  'Stony Brook Robotics Team',
  'Stony Brook Science Olympiad',
  'Stony Brook Vocalists',
  'Synthetic Biology Society',
  'Table Tennis Club',
  'The Statesman',
  'Ultimate Frisbee',
  'Undergraduate Biochemistry Society',
  'Undergraduate Student Government',
  'Women in Business',
  'Women in Computer Science',
  "Women's Lacrosse",
  "Women's Rugby",
  'WUSB Radio',
]
