export const MAJORS: string[] = [
  "Africana Studies",
  "American Studies",
  "Anthropology",
  "Applied Mathematics",
  "Applied Mathematics-Biology",
  "Applied Mathematics-Computer Science",
  "Applied Mathematics-Economics",
  "Archaeology and the Ancient World",
  "Architecture",
  "Astronomy",
  "Behavioral Decision Sciences",
  "Biochemistry & Molecular Biology",
  "Biology",
  "Biomedical Engineering",
  "Biophysics",
  "Chemical Engineering",
  "Chemical Physics",
  "Chemistry",
  "Classics",
  "Cognitive Neuroscience",
  "Cognitive Science",
  "Comparative Literature",
  "Computational Biology",
  "Computational Chemistry and Chemical Physics",
  "Computational Neuroscience",
  "Computer Engineering",
  "Computer Science",
  "Computer Science-Economics",
  "Contemplative Studies",
  "Critical Native American and Indigenous Studies",
  "Design Engineering",
  "Early Modern World",
  "Earth and Planetary Science",
  "Earth, Climate, and Biology",
  "East Asian Studies",
  "Economics",
  "Education Studies",
  "Egyptology and Assyriology",
  "Electrical Engineering",
  "Engineering",
  "Engineering and Physics",
  "English",
  "Environmental Engineering",
  "Environmental Sciences and Studies",
  "Ethnic Studies",
  "French and Francophone Studies",
  "Gender and Sexuality Studies",
  "Geochemistry and Environmental Chemistry",
  "Geophysics and Climate Physics",
  "German Studies",
  "Health & Human Biology",
  "Hispanic Literatures and Cultures",
  "History",
  "History of Art and Architecture",
  "International and Public Affairs",
  "Italian Studies",
  "Judaic Studies",
  "Latin American and Caribbean Studies",
  "Linguistics",
  "Literary Arts",
  "Materials Engineering",
  "Mathematics",
  "Mathematics-Computer Science",
  "Mathematics-Economics",
  "Mechanical Engineering",
  "Medieval Cultures",
  "Middle East Studies",
  "Modern Culture and Media",
  "Music",
  "Neuroscience",
  "Philosophy",
  "Physics",
  "Physics and Philosophy",
  "Political Science",
  "Portuguese and Brazilian Studies",
  "Psychology",
  "Public Health",
  "Religious Studies",
  "Science, Technology, and Society",
  "Slavic Studies",
  "Social Analysis and Research",
  "Sociology",
  "South Asian Studies",
  "Statistics",
  "Theatre Arts and Performance Studies",
  "Urban Studies",
  "Visual Art",
]

export const MINORS: string[] = [
  "Data Fluency",
  "Engaged Scholarship",
  "Entrepreneurship",
  "European Critical Thought",
  "Intercultural Competence",
  "Migration Studies",
]

export const COURSES: Record<string, { name: string; courses: string[] }> = {}
export const CLUBS: string[] = []
export const GREEK_LIFE: string[] = []
export const RESIDENCE_HALLS: { value: string; label: string; group?: string }[] = []
