export const MAJORS: string[] = [
  "Applied & Computational Mathematics",
  "Applied Physics",
  "Astrophysics",
  "Bioengineering",
  "Biology",
  "Business, Economics & Management",
  "Chemical Engineering",
  "Chemistry",
  "Computation & Neural Systems",
  "Computer Science",
  "Economics",
  "Electrical Engineering",
  "Engineering & Applied Science",
  "English",
  "Environmental Science & Engineering",
  "Geological & Planetary Sciences",
  "History",
  "History & Philosophy of Science",
  "Information & Data Sciences",
  "Interdisciplinary Studies Program",
  "Materials Science",
  "Mathematics",
  "Mechanical Engineering",
  "Philosophy",
  "Physics",
  "Political Science",
]

export const MINORS: string[] = [
  "Aerospace",
  "Applied & Computational Mathematics",
  "Astrophysics",
  "Bioengineering",
  "Biology",
  "Business, Economics & Management",
  "Chemical Engineering",
  "Chemistry",
  "Computer Science",
  "Control & Dynamical Systems",
  "Electrical Engineering",
  "English",
  "Environmental Science & Engineering",
  "Geological & Planetary Sciences",
  "History",
  "History & Philosophy of Science",
  "Information & Data Sciences",
  "Materials Science",
  "Mathematics",
  "Mechanical Engineering",
  "Neurobiology",
  "Philosophy",
  "Physics",
  "Political Science",
  "Robotics",
  "Structural Mechanics",
  "Visual Culture",
]

export const COURSES: Record<string, { name: string; courses: string[] }> = {}
export const CLUBS: string[] = []
export const GREEK_LIFE: string[] = []
export const RESIDENCE_HALLS: { value: string; label: string; group?: string }[] = []
