export const MAJORS: string[] = [
  "Applied and Computational Mathematics",
  "Applied Physics",
  "Astrophysics",
  "Bioengineering",
  "Biology",
  "Business, Economics, and Management",
  "Chemical Engineering",
  "Chemistry",
  "Computation and Neural Systems",
  "Computer Science",
  "Economics",
  "Electrical Engineering",
  "Engineering and Applied Science",
  "English",
  "Environmental Science and Engineering",
  "Geological and Planetary Sciences",
  "History",
  "History and Philosophy of Science",
  "Information and Data Sciences",
  "Interdisciplinary Studies Program",
  "Materials Science",
  "Mathematics",
  "Mechanical Engineering",
  "Philosophy",
  "Physics",
  "Political Science",
]

export const MINORS: string[] = [
  "Aerospace",
  "Astrophysics",
  "Biology",
  "Chemical Engineering",
  "Chemistry",
  "Computer Science",
  "Control and Dynamical Systems",
  "English",
  "Environmental Science and Engineering",
  "Geological and Planetary Sciences",
  "History",
  "History and Philosophy of Science",
  "Information and Data Sciences",
  "Mathematics",
  "Neurobiology",
  "Philosophy",
  "Robotics",
  "Structural Mechanics",
  "Visual Culture",
]

export const COURSES: Record<string, { name: string; courses: string[] }> = {}
export const CLUBS: string[] = []
export const GREEK_LIFE: string[] = []
export const RESIDENCE_HALLS: { value: string; label: string; group?: string }[] = []
