export const MAJORS: string[] = [
  "African American and African Diaspora Studies",
  "American Studies",
  "Ancient Studies",
  "Anthropology",
  "Applied Mathematics",
  "Applied Physics",
  "Archaeology",
  "Architecture",
  "Art History and Visual Arts",
  "Astronomy and Astrophysics",
  "Biochemistry",
  "Biology",
  "Biophysics",
  "Biomedical Engineering",
  "Chemical Engineering",
  "Chemical Physics",
  "Chemistry",
  "Civil Engineering",
  "Classics",
  "Comparative Ethnic Studies",
  "Comparative Literature and Society",
  "Computer Engineering",
  "Computer Science",
  "Computer Science-Mathematics",
  "Creative Writing",
  "Dance",
  "Drama and Theatre Arts",
  "Earth and Environmental Engineering",
  "Earth and Environmental Sciences",
  "East Asian Studies",
  "Economics",
  "Economics-Mathematics",
  "Economics-Philosophy",
  "Economics-Political Science",
  "Economics-Statistics",
  "Electrical Engineering",
  "Engineering Management Systems",
  "Engineering Mechanics",
  "English and Comparative Literature",
  "Environmental Biology",
  "Environmental Chemistry",
  "Environmental Science",
  "Ethnicity and Race Studies",
  "Evolutionary Biology of the Human Species",
  "Film and Media Studies",
  "Financial Economics",
  "French and Romance Philology",
  "Germanic Languages",
  "Hispanic Studies",
  "History",
  "History and Philosophy of Science",
  "Human Rights",
  "Industrial Engineering",
  "Information Science",
  "Italian",
  "Latin American and Caribbean Studies",
  "Linguistics",
  "Materials Science and Engineering",
  "Mathematics",
  "Mathematics-Statistics",
  "Mechanical Engineering",
  "Medieval and Renaissance Studies",
  "Middle Eastern, South Asian, and African Studies",
  "Music",
  "Neuroscience and Behavior",
  "Operations Research",
  "Philosophy",
  "Physics",
  "Political Science",
  "Political Science-Statistics",
  "Psychology",
  "Regional Studies",
  "Religion",
  "Russian Language and Culture",
  "Slavic Studies",
  "Sociology",
  "Statistics",
  "Sustainable Development",
  "Urban Studies",
  "Visual Arts",
  "Women's and Gender Studies",
  "Yiddish Studies",
]

export const MINORS: string[] = [
  "African American and African Diaspora Studies",
  "American Studies",
  "Ancient Studies",
  "Anthropology",
  "Applied Mathematics",
  "Archaeology",
  "Architecture",
  "Art History",
  "Astronomy",
  "Biology",
  "Business Management",
  "Chemistry",
  "Classics",
  "Comparative Ethnic Studies",
  "Comparative Literature and Society",
  "Computer Science",
  "Creative Writing",
  "Dance",
  "Drama and Theatre Arts",
  "East Asian Studies",
  "Economics",
  "Education Studies",
  "English",
  "Entrepreneurship",
  "Environmental Science",
  "Ethnicity and Race Studies",
  "Film and Media Studies",
  "French",
  "Germanic Languages",
  "Hispanic Studies",
  "History",
  "Human Rights",
  "Italian",
  "Jazz Studies",
  "Latin American and Caribbean Studies",
  "Linguistics",
  "Mathematics",
  "Medieval and Renaissance Studies",
  "Middle Eastern, South Asian, and African Studies",
  "Music",
  "Neuroscience and Behavior",
  "Philosophy",
  "Physics",
  "Political Science",
  "Psychology",
  "Religion",
  "Russian Language and Culture",
  "Slavic Studies",
  "Sociology",
  "Statistics",
  "Sustainable Development",
  "Urban Studies",
  "Visual Arts",
  "Women's and Gender Studies",
]

export const COURSES: Record<string, { name: string; courses: string[] }> = {}
export const CLUBS: string[] = []
export const GREEK_LIFE: string[] = []
export const RESIDENCE_HALLS: { value: string; label: string; group?: string }[] = []
