export const MAJORS: string[] = [
  "African American and African Diaspora Studies",
  "American Studies",
  "Ancient Studies",
  "Anthropology",
  "Applied Mathematics",
  "Applied Physics",
  "Archaeology",
  "Architecture",
  "Art History",
  "Art History and Visual Arts",
  "Astronomy",
  "Astrophysics",
  "Biochemistry",
  "Biology",
  "Biomedical Engineering",
  "Biophysics",
  "Chemical Engineering",
  "Chemical Physics",
  "Chemistry",
  "Civil Engineering",
  "Classics",
  "Climate and Sustainability",
  "Climate System Science",
  "Cognitive Science",
  "Comparative Literature and Society",
  "Computational Biology",
  "Computer Engineering",
  "Computer Science",
  "Computer Science-Mathematics",
  "Creative Writing",
  "Dance",
  "Data Science",
  "Drama and Theatre Arts",
  "Earth and Environmental Engineering",
  "Earth Science",
  "East Asian Languages and Cultures",
  "Economics",
  "Economics-Mathematics",
  "Economics-Philosophy",
  "Economics-Political Science",
  "Economics-Statistics",
  "Education Studies",
  "Electrical Engineering",
  "Engineering Mechanics",
  "English and Comparative Literature",
  "Environmental Biology",
  "Environmental Chemistry",
  "Environmental Science",
  "Ethnicity and Race Studies",
  "Evolutionary Biology of the Human Species",
  "Film and Media Studies",
  "Financial Economics",
  "French and Francophone Studies",
  "German Literature and Cultural History",
  "Hispanic Studies",
  "History",
  "History and Theory of Architecture",
  "Human Rights",
  "Industrial Engineering",
  "Information Science",
  "Italian",
  "Jazz Studies",
  "Jewish Studies",
  "Latin American and Caribbean Studies",
  "Linguistics",
  "Materials Science and Engineering",
  "Mathematics",
  "Mathematics-Statistics",
  "Mechanical Engineering",
  "Medical Humanities",
  "Medieval and Renaissance Studies",
  "Middle Eastern, South Asian, and African Studies",
  "Modern Greek Studies",
  "Music",
  "Neuroscience and Behavior",
  "Operations Research",
  "Philosophy",
  "Physics",
  "Political Science",
  "Political Science-Statistics",
  "Portuguese Studies",
  "Psychology",
  "Regional Studies",
  "Religion",
  "Russian Language and Culture",
  "Russian Literature and Culture",
  "Slavic Studies",
  "Sociology",
  "Statistics",
  "Sustainable Development",
  "Urban Studies",
  "Visual Arts",
  "Women's and Gender Studies",
  "Yiddish Studies",
]

export const MINORS: string[] = [
  "African American Studies",
  "American Studies",
  "Anthropology",
  "Archaeology",
  "Architecture",
  "Art History",
  "Artificial Intelligence",
  "Astronomy",
  "Biology",
  "Chemistry",
  "Classics",
  "Climate System Science",
  "Computer Science",
  "Dance",
  "Drama and Theatre Arts",
  "Earth and Environmental Science",
  "East Asian Studies",
  "Education Studies",
  "English",
  "Film and Media Studies",
  "French and Francophone Studies",
  "German",
  "Hellenic Studies",
  "Hispanic Cultures",
  "History",
  "History and Theory of Architecture",
  "Human Rights",
  "Italian",
  "Jewish Studies",
  "Latin American and Caribbean Studies",
  "Linguistics",
  "Mathematics",
  "Medieval and Renaissance Studies",
  "Music",
  "Philosophy",
  "Physics",
  "Political Science",
  "Portuguese",
  "Religion",
  "Slavic and Eastern European Culture",
  "Sociology",
  "Statistics",
  "Sustainable Development",
  "Visual Arts",
  "Women's and Gender Studies",
  "Yiddish Studies",
]

export const COURSES: Record<string, { name: string; courses: string[] }> = {}
export const CLUBS: string[] = []
export const GREEK_LIFE: string[] = []
export const RESIDENCE_HALLS: { value: string; label: string; group?: string }[] = []
