export const MAJORS: string[] = [
  "African and African American Studies",
  "Ancient History",
  "Anthropology",
  "Applied Mathematics for Biological and Social Sciences",
  "Applied Mathematics for Physical and Engineering Sciences",
  "Art History",
  "Asian Societies, Cultures, and Languages",
  "Astronomy",
  "Biological Chemistry",
  "Biological Sciences",
  "Biomedical Engineering Sciences",
  "Biophysical Chemistry",
  "Chemistry",
  "Classical Archaeology",
  "Classical Languages and Literatures",
  "Classical Studies",
  "Cognitive Science",
  "Comparative Literature",
  "Computer Science",
  "Earth Sciences",
  "East European, Eurasian, and Russian Studies",
  "Economics",
  "Engineering Physics",
  "Engineering Sciences",
  "English",
  "Environmental Earth Sciences",
  "Environmental Studies",
  "Film and Media Studies",
  "French",
  "French Studies",
  "Geography",
  "German Studies",
  "Government",
  "History",
  "Italian",
  "Italian Studies",
  "Latin American, Latino, and Caribbean Studies",
  "Linguistics",
  "Mathematical Data Science",
  "Mathematics",
  "Medieval and Renaissance Studies",
  "Middle Eastern Studies",
  "Music",
  "Native American and Indigenous Studies",
  "Neuroscience",
  "Philosophy",
  "Physics",
  "Portuguese (Lusophone Studies)",
  "Psychology",
  "Quantitative Social Science",
  "Religion",
  "Romance Languages",
  "Romance Studies",
  "Sociology",
  "Spanish (Hispanic Studies)",
  "Studio Art",
  "Theater",
  "Women's, Gender, and Sexuality Studies",
]

export const MINORS: string[] = [
  "African and African American Studies",
  "Anthropology",
  "Applied Mathematics for Biological and Social Sciences",
  "Applied Mathematics for Physical and Engineering Sciences",
  "Art History",
  "Asian Societies, Cultures, and Languages",
  "Astronomy",
  "Biological Sciences",
  "Chemistry",
  "Classical Studies",
  "Cognitive Science",
  "Comparative Literature",
  "Complex Systems",
  "Computer Science",
  "Digital Arts",
  "Earth Sciences",
  "Economics",
  "Education",
  "Engineering Sciences",
  "English",
  "Environmental Science",
  "Environmental Studies",
  "Film and Media Studies",
  "French",
  "Geography",
  "German Studies",
  "Global Health",
  "Government",
  "History",
  "Human-Centered Design",
  "International Studies",
  "Italian",
  "Jewish Studies",
  "Latin American, Latino, and Caribbean Studies",
  "Linguistics",
  "Markets, Management, and the Economy",
  "Materials Science",
  "Mathematical Biology",
  "Mathematical Finance",
  "Mathematical Logic",
  "Mathematical Physics",
  "Mathematics",
  "Medieval and Renaissance Studies",
  "Middle Eastern Studies",
  "Music",
  "Native American and Indigenous Studies",
  "Neuroscience",
  "Philosophy",
  "Physics",
  "Portuguese (Lusophone Studies)",
  "Psychology",
  "Public Policy",
  "Quantitative Social Science",
  "Religion",
  "Social Inequalities",
  "Sociology",
  "Spanish (Hispanic Studies)",
  "Statistics",
  "Studio Art",
  "Sustainability",
  "Theater",
  "Urban Studies",
  "Women's, Gender, and Sexuality Studies",
]

export const COURSES: Record<string, { name: string; courses: string[] }> = {}
export const CLUBS: string[] = []
export const GREEK_LIFE: string[] = []
export const RESIDENCE_HALLS: { value: string; label: string; group?: string }[] = []
