export const MAJORS: string[] = [
  "African and African American Studies",
  "Anthropology",
  "Applied Mathematics",
  "Art, Film, and Visual Studies",
  "Astrophysics",
  "Biomedical Engineering",
  "Chemical and Physical Biology",
  "Chemistry",
  "Chemistry and Physics",
  "Classics",
  "Comparative Literature",
  "Comparative Study of Religion",
  "Computer Science",
  "Earth and Planetary Sciences",
  "East Asian Studies",
  "Economics",
  "Electrical Engineering",
  "Engineering Sciences",
  "English",
  "Environmental Science and Engineering",
  "Environmental Science and Public Policy",
  "Folklore and Mythology",
  "Germanic Languages and Literatures",
  "Government",
  "History",
  "History and Literature",
  "History and Science",
  "History of Art and Architecture",
  "Human Developmental and Regenerative Biology",
  "Human Evolutionary Biology",
  "Integrative Biology",
  "Linguistics",
  "Mathematics",
  "Mechanical Engineering",
  "Molecular and Cellular Biology",
  "Music",
  "Near Eastern Languages and Civilizations",
  "Neuroscience",
  "Philosophy",
  "Physics",
  "Psychology",
  "Romance Languages and Literatures",
  "Slavic Languages and Literatures",
  "Social Studies",
  "Sociology",
  "South Asian Studies",
  "Statistics",
  "Theater, Dance, and Media",
  "Women, Gender, and Sexuality",
]

export const MINORS: string[] = [
  "African and African American Studies",
  "Anthropology",
  "Applied Mathematics",
  "Archaeology",
  "Art, Film, and Visual Studies",
  "Astrophysics",
  "Celtic Languages and Literatures",
  "Chemistry",
  "Classics",
  "Comparative Literature",
  "Comparative Study of Religion",
  "Computer Science",
  "Data Science",
  "Earth and Planetary Sciences",
  "East Asian Studies",
  "Economics",
  "Energy and Environment",
  "English",
  "Ethnicity, Migration, Rights",
  "Folklore and Mythology",
  "Germanic Languages and Literatures",
  "Global Health and Health Policy",
  "Government",
  "History",
  "History and Science",
  "History of Art and Architecture",
  "Human Evolutionary Biology",
  "Linguistics",
  "Mathematics",
  "Medieval Studies",
  "Mind, Brain, and Behavior",
  "Molecular and Cellular Biology",
  "Music",
  "Near Eastern Languages and Civilizations",
  "Neuroscience",
  "Philosophy",
  "Physics",
  "Psychology",
  "Romance Languages and Literatures",
  "Slavic Languages and Literatures",
  "Social Studies",
  "Sociology",
  "South Asian Studies",
  "Statistics",
  "Theater, Dance, and Media",
  "Translation Studies",
  "Women, Gender, and Sexuality",
]

export const COURSES: Record<string, { name: string; courses: string[] }> = {}
export const CLUBS: string[] = []
export const GREEK_LIFE: string[] = []
export const RESIDENCE_HALLS: { value: string; label: string; group?: string }[] = []
