export const MAJORS: string[] = [
  "African American Studies",
  "Anthropology",
  "Architecture",
  "Art & Archaeology",
  "Astrophysical Sciences",
  "Chemical and Biological Engineering",
  "Chemistry",
  "Civil and Environmental Engineering",
  "Classics",
  "Comparative Literature",
  "Computer Science",
  "East Asian Studies",
  "Ecology and Evolutionary Biology",
  "Economics",
  "Electrical and Computer Engineering",
  "English",
  "French and Italian",
  "Geosciences",
  "German",
  "History",
  "Mathematics",
  "Mechanical and Aerospace Engineering",
  "Molecular Biology",
  "Music",
  "Near Eastern Studies",
  "Neuroscience",
  "Operations Research and Financial Engineering",
  "Philosophy",
  "Physics",
  "Politics",
  "Psychology",
  "Public Policy",
  "Religion",
  "Slavic Languages and Literatures",
  "Sociology",
  "Spanish and Portuguese",
]

export const MINORS: string[] = [
  "African American Studies",
  "African Studies",
  "American Studies",
  "Applied and Computational Mathematics",
  "Arabic Language",
  "Archaeology",
  "Architecture and Engineering",
  "Asian American Studies",
  "Bioengineering",
  "Chinese Language",
  "Classics",
  "Climate Sciences",
  "Cognitive Science",
  "Computer Science",
  "Computing, Society and Policy",
  "Creative Writing",
  "Dance",
  "East Asian Studies",
  "Engineering Physics",
  "English",
  "Entrepreneurship",
  "Environmental Studies",
  "European Cultural Studies",
  "European Studies",
  "Finance",
  "French and Italian",
  "Gender and Sexuality Studies",
  "German Language and Culture",
  "Global Health and Health Policy",
  "Hebrew Language",
  "Hellenic Studies",
  "History",
  "History and the Practice of Diplomacy",
  "History of Art",
  "History of Science, Technology, and Medicine",
  "Humanistic Studies",
  "Japanese Language",
  "Journalism",
  "Judaic Studies",
  "Korean Language",
  "Latin American Studies",
  "Latino Studies",
  "Linguistics",
  "Materials Science and Engineering",
  "Mathematics",
  "Medieval Studies",
  "Music",
  "Music Performance",
  "Near Eastern Studies",
  "Neuroscience",
  "Optimization and Quantitative Decision Science",
  "Persian Language",
  "Philosophy",
  "Planets and Life",
  "Quantitative and Computational Biology",
  "Quantitative Economics",
  "Religion",
  "Robotics",
  "Russian, East European and Eurasian Studies",
  "Slavic Languages and Culture",
  "South Asian Studies",
  "Spanish and Portuguese",
  "Statistics and Machine Learning",
  "Sustainable Energy",
  "Teacher Preparation",
  "Technology and Society",
  "Theater and Music Theater",
  "Translation and Intercultural Communication",
  "Urban Studies",
  "Values and Public Life",
  "Visual Arts",
]

export const COURSES: Record<string, { name: string; courses: string[] }> = {}
export const CLUBS: string[] = []
export const GREEK_LIFE: string[] = []
export const RESIDENCE_HALLS: { value: string; label: string; group?: string }[] = []
