export const MAJORS: string[] = [
  "African American Studies",
  "Anthropology",
  "Architecture",
  "Art and Archaeology",
  "Astrophysical Sciences",
  "Chemical and Biological Engineering",
  "Chemistry",
  "Civil and Environmental Engineering",
  "Classics",
  "Comparative Literature",
  "Computer Science",
  "East Asian Studies",
  "Ecology and Evolutionary Biology",
  "Economics",
  "Electrical and Computer Engineering",
  "English",
  "French and Italian",
  "Geosciences",
  "German",
  "History",
  "Mathematics",
  "Mechanical and Aerospace Engineering",
  "Molecular Biology",
  "Music",
  "Near Eastern Studies",
  "Neuroscience",
  "Operations Research and Financial Engineering",
  "Philosophy",
  "Physics",
  "Politics",
  "Psychology",
  "Religion",
  "Slavic Languages and Literatures",
  "Sociology",
  "Spanish and Portuguese",
  "Statistics and Machine Learning",
]

export const MINORS: string[] = [
  "African American Studies",
  "African Studies",
  "American Studies",
  "Applied and Computational Mathematics",
  "Architecture",
  "Asian American Studies",
  "Bioengineering",
  "Classics",
  "Climate Science",
  "Cognitive Science",
  "Computer Science",
  "Contemporary European Politics and Society",
  "Creative Writing",
  "Dance",
  "East Asian Studies",
  "Engineering Physics",
  "English",
  "Entrepreneurship",
  "Environmental Studies",
  "European Studies",
  "Finance",
  "Gender and Sexuality Studies",
  "Global Health and Health Policy",
  "History",
  "History of Art",
  "History of Science, Technology, and Medicine",
  "Humanistic Studies",
  "Jazz Studies",
  "Journalism",
  "Judaic Studies",
  "Language and Culture",
  "Latin American Studies",
  "Linguistics",
  "Materials Science and Engineering",
  "Mathematics",
  "Media and Modernity",
  "Medieval Studies",
  "Music Performance",
  "Music Theater",
  "Near Eastern Studies",
  "Neuroscience",
  "Planets and Life",
  "Quantitative Economics",
  "Religion",
  "Robotics",
  "Russian, East European, and Eurasian Studies",
  "South Asian Studies",
  "Statistics and Machine Learning",
  "Sustainable Energy",
  "Teacher Preparation",
  "Technology and Society",
  "Theater",
  "Translation and Intercultural Communication",
  "Urban Studies",
  "Values and Public Life",
  "Visual Arts",
]

export const COURSES: Record<string, { name: string; courses: string[] }> = {}
export const CLUBS: string[] = []
export const GREEK_LIFE: string[] = []
export const RESIDENCE_HALLS: { value: string; label: string; group?: string }[] = []
