export const MAJORS: string[] = [
  "Aeronautics & Astronautics",
  "African & African American Studies",
  "American Studies",
  "Anthropology",
  "Applied Mathematics",
  "Archaeology",
  "Art History",
  "Art Practice",
  "Asian American Studies",
  "Astrophysics",
  "Bioengineering",
  "Biology",
  "Biomedical Computation",
  "Chemical Engineering",
  "Chemistry",
  "Chicana/o-Latina/o Studies",
  "Chinese",
  "Civil & Environmental Engineering",
  "Classics",
  "Cognitive Science",
  "Communication",
  "Community Health & Prevention Research",
  "Comparative Literature",
  "Comparative Studies in Race & Ethnicity",
  "Computer Science",
  "Data Science",
  "Earth & Planetary Sciences",
  "Earth Systems",
  "East Asian Studies",
  "Economics",
  "Electrical Engineering",
  "Engineering",
  "Engineering Physics",
  "English",
  "Environmental Systems Engineering",
  "Film & Media Studies",
  "French",
  "Geological Sciences",
  "Geophysics",
  "German Studies",
  "History",
  "Human Biology",
  "International Relations",
  "Italian",
  "Japanese",
  "Linguistics",
  "Management Science & Engineering",
  "Materials Science & Engineering",
  "Mathematical & Computational Science",
  "Mathematics",
  "Mechanical Engineering",
  "Music",
  "Native American Studies",
  "Philosophy",
  "Philosophy & Religious Studies",
  "Physics",
  "Political Science",
  "Product Design",
  "Psychology",
  "Public Policy",
  "Religious Studies",
  "Science, Technology & Society",
  "Sociology",
  "Spanish",
  "Symbolic Systems",
  "Theater & Performance Studies",
  "Urban Studies",
]

export const MINORS: string[] = [
  "Aeronautics & Astronautics",
  "African & African American Studies",
  "Anthropology",
  "Applied Physics",
  "Archaeology",
  "Art History",
  "Art Practice",
  "Asian American Studies",
  "Bioengineering",
  "Biology",
  "Biomedical Computation",
  "Chemical Engineering",
  "Chemistry",
  "Chicana/o-Latina/o Studies",
  "Chinese",
  "Civil & Environmental Engineering",
  "Classics",
  "Communication",
  "Comparative Literature",
  "Comparative Studies in Race & Ethnicity",
  "Computer Science",
  "Creative Writing",
  "Dance",
  "Data Science",
  "Earth & Planetary Sciences",
  "East Asian Studies",
  "Economics",
  "Education",
  "Electrical Engineering",
  "English",
  "Ethics in Society",
  "Feminist, Gender & Sexuality Studies",
  "Film & Media Studies",
  "French",
  "German Studies",
  "History",
  "Human Biology",
  "Human Rights",
  "International Relations",
  "Italian",
  "Japanese",
  "Jewish Studies",
  "Korean",
  "Linguistics",
  "Materials Science & Engineering",
  "Mathematics",
  "Mechanical Engineering",
  "Medieval Studies",
  "Music",
  "Philosophy",
  "Physics",
  "Political Science",
  "Psychology",
  "Public Policy",
  "Religious Studies",
  "Russian",
  "Science, Technology & Society",
  "Sociology",
  "Spanish",
  "Statistics",
  "Sustainability",
  "Symbolic Systems",
  "Theater & Performance Studies",
  "Translation Studies",
  "Urban Studies",
]

export const COURSES: Record<string, { name: string; courses: string[] }> = {}
export const CLUBS: string[] = []
export const GREEK_LIFE: string[] = []
export const RESIDENCE_HALLS: { value: string; label: string; group?: string }[] = []
