export const MAJORS: string[] = [
  "Aeronautics and Astronautics",
  "African and African American Studies",
  "American Studies",
  "Anthropology",
  "Applied Physics",
  "Archaeology",
  "Art History",
  "Art Practice",
  "Asian American Studies",
  "Atmosphere/Energy",
  "Bioengineering",
  "Biology",
  "Biomechanical Engineering",
  "Biomedical Computation",
  "Chemical Engineering",
  "Chemistry",
  "Chicana/o - Latina/o Studies",
  "China Studies",
  "Civil Engineering",
  "Classics",
  "Communication",
  "Community Health and Prevention Research",
  "Comparative Literature",
  "Comparative Studies in Race and Ethnicity",
  "Computer Science",
  "Data Science",
  "Data Science & Social Systems",
  "Earth and Planetary Sciences",
  "Earth Systems",
  "East Asian Studies",
  "Economics",
  "Electrical Engineering",
  "Energy Science and Engineering",
  "Engineering Physics",
  "English",
  "Environmental Systems Engineering",
  "Film and Media Studies",
  "French",
  "Geophysics",
  "German Studies",
  "History",
  "Human Biology",
  "International Relations",
  "Italian",
  "Japanese",
  "Linguistics",
  "Management Science and Engineering",
  "Materials Science and Engineering",
  "Mathematical and Computational Science",
  "Mathematics",
  "Mechanical Engineering",
  "Music",
  "Native American Studies",
  "Philosophy",
  "Philosophy and Religious Studies",
  "Physics",
  "Political Science",
  "Psychology",
  "Public Policy",
  "Religious Studies",
  "Science, Technology, and Society",
  "Sociology",
  "Spanish",
  "Symbolic Systems",
  "Theater and Performance Studies",
  "Urban Studies",
]

export const MINORS: string[] = [
  "Aeronautics and Astronautics",
  "African and African American Studies",
  "African Studies",
  "American Studies",
  "Anthropology",
  "Applied Physics",
  "Archaeology",
  "Art History",
  "Art Practice",
  "Asian American Studies",
  "Atmosphere/Energy",
  "Bioengineering",
  "Biology",
  "Biomechanical Engineering",
  "Biomedical Computation",
  "Chemical Engineering",
  "Chemistry",
  "Chicana/o - Latina/o Studies",
  "China Studies",
  "Civil Engineering",
  "Classics",
  "Communication",
  "Community Health and Prevention Research",
  "Comparative Literature",
  "Comparative Studies in Race and Ethnicity",
  "Computer Science",
  "Creative Writing",
  "Dance",
  "Data Science",
  "Data Science & Social Systems",
  "Democracy, Development, and the Rule of Law",
  "Design",
  "Digital Humanities",
  "Earth and Planetary Sciences",
  "Earth Systems",
  "East Asian Studies",
  "Economics",
  "Education",
  "Electrical Engineering",
  "Energy Science and Engineering",
  "Engineering Physics",
  "English",
  "Environmental Systems Engineering",
  "Ethics in Society",
  "European Studies",
  "Feminist, Gender, and Sexuality Studies",
  "Film and Media Studies",
  "French",
  "Geophysics",
  "German Studies",
  "Global Studies",
  "History",
  "Honors in the Arts",
  "Human Biology",
  "Human Rights",
  "Iberian and Latin American Cultures",
  "International Policy Studies",
  "International Relations",
  "International Security Studies",
  "Iranian Studies",
  "Islamic Studies",
  "Italian",
  "Japanese",
  "Jewish Studies",
  "Korean",
  "Laboratory Animal Science",
  "Latin American Studies",
  "Linguistics",
  "Management Science and Engineering",
  "Materials Science and Engineering",
  "Mathematical and Computational Science",
  "Mathematics",
  "Mechanical Engineering",
  "Medieval Studies",
  "Middle Eastern Language, Literature and Culture",
  "Modern Languages",
  "Modern Thought and Literature",
  "Music",
  "Music, Science, and Technology",
  "Native American Studies",
  "Philosophy",
  "Philosophy and Religious Studies",
  "Physics",
  "Political Science",
  "Portuguese",
  "Psychology",
  "Public Policy",
  "Religious Studies",
  "Science, Technology, and Society",
  "Slavic Languages and Literatures",
  "Sociology",
  "South Asian Studies",
  "Spanish",
  "Statistics",
  "Sustainability",
  "Sustainable Architecture + Engineering",
  "Symbolic Systems",
  "Theater and Performance Studies",
  "Translation Studies",
  "Urban Studies",
]

export const COURSES: Record<string, { name: string; courses: string[] }> = {}
export const CLUBS: string[] = []
export const GREEK_LIFE: string[] = []
export const RESIDENCE_HALLS: { value: string; label: string; group?: string }[] = []
