export const MAJORS: string[] = [
  "Accounting",
  "Africana Studies",
  "Ancient History",
  "Anthropology",
  "Architecture",
  "Artificial Intelligence for Business",
  "Behavioral Economics",
  "Biochemistry",
  "Bioengineering",
  "Biology",
  "Biophysics",
  "Business Analytics",
  "Business Economics & Public Policy",
  "Chemical & Biomolecular Engineering",
  "Chemistry",
  "Cinema & Media Studies",
  "Classical Studies",
  "Cognitive Science",
  "Communication",
  "Comparative Literature",
  "Computer Engineering",
  "Computer Science",
  "Criminology",
  "Design",
  "Earth & Environmental Science",
  "East Asian Languages & Civilizations",
  "Economics",
  "Electrical Engineering",
  "English",
  "Entrepreneurship & Innovation",
  "Environmental Studies",
  "Environmental, Social & Governance Factors for Business",
  "Finance",
  "Fine Arts",
  "Francophone, Italian & Germanic Studies",
  "Gender, Sexuality & Women's Studies",
  "Health & Societies",
  "Health Care Management & Policy",
  "Hispanic Studies",
  "History",
  "History of Art",
  "Individualized Major",
  "International Relations",
  "International Studies",
  "Jewish Studies",
  "Latin American & Latinx Studies",
  "Law & Society",
  "Leading Across Differences",
  "Legal Studies & Business Ethics",
  "Linguistics",
  "Logic, Information & Computation",
  "Management",
  "Marketing",
  "Marketing & Communication",
  "Marketing & Operations Management",
  "Materials Science & Engineering",
  "Mathematical Economics",
  "Mathematics",
  "Mechanical Engineering & Applied Mechanics",
  "Middle Eastern Languages & Cultures",
  "Modern Middle Eastern Studies",
  "Music",
  "Neuroscience",
  "Nursing",
  "Nutrition Science",
  "Operations, Information & Decisions",
  "Philosophy",
  "Philosophy, Politics & Economics",
  "Physics",
  "Political Science",
  "Psychology",
  "Real Estate",
  "Religious Studies",
  "Retailing",
  "Russian & East European Studies",
  "Science, Technology & Society",
  "Sociology",
  "South Asia Studies",
  "Statistics & Data Science",
  "Systems Science & Engineering",
  "Theatre Arts",
  "Urban Studies",
  "Visual Studies",
]

export const MINORS: string[] = [
  "Africana Studies",
  "American Public Policy",
  "American Sign Language & Deaf Studies",
  "Ancient History",
  "Anthropology",
  "Archaeological Science",
  "Architectural History",
  "Architecture",
  "Asian American Studies",
  "Bioethics",
  "Biology",
  "Biophysics",
  "Chemical & Biomolecular Engineering",
  "Chemistry",
  "Cinema & Media Studies",
  "Classical Studies",
  "Cognitive Science",
  "Comparative Literature",
  "Computational Neuroscience",
  "Computer & Information Science",
  "Consumer Psychology",
  "Creative Writing",
  "Data Science",
  "Data Science & Analytics",
  "Design",
  "Digital Humanities",
  "Digital Media Design",
  "East Asian Area Studies",
  "East Asian Languages & Civilizations (Chinese)",
  "East Asian Languages & Civilizations (Japanese)",
  "East Asian Languages & Civilizations (Korean)",
  "Economic Policy",
  "Economics",
  "Electrical & Systems Engineering",
  "Energy & Sustainability",
  "Engineering Entrepreneurship",
  "English",
  "Environmental Humanities",
  "Environmental Science",
  "Environmental Studies",
  "European Studies",
  "Fine Arts",
  "French & Francophone Studies",
  "Gender, Sexuality & Women's Studies",
  "Geology",
  "German",
  "Global Medieval Studies",
  "Hispanic Studies",
  "History",
  "History of Art",
  "International Development",
  "International Relations",
  "Italian Studies",
  "Jewish Studies",
  "Journalistic Writing",
  "Landscape Studies",
  "Latin American & Latinx Studies",
  "Law & Society",
  "Legal Studies & History",
  "Linguistics",
  "Logic, Information & Computation",
  "Materials Science & Engineering",
  "Mathematics",
  "Mechanical Engineering & Applied Mechanics",
  "Medical Sociology",
  "Middle Eastern Languages & Cultures (Ancient Middle East)",
  "Middle Eastern Languages & Cultures (Arabic & Hebrew Studies)",
  "Middle Eastern Languages & Cultures (Arabic & Islamic Studies)",
  "Middle Eastern Languages & Cultures (Cultures & Societies of MENA)",
  "Middle Eastern Languages & Cultures (Hebrew & Judaica)",
  "Middle Eastern Languages & Cultures (Persian Language & Literature)",
  "Modern Middle Eastern Studies",
  "Music",
  "Native American & Indigenous Studies",
  "Neuroscience",
  "Neuroscience & Health Care Management",
  "Nutrition",
  "Philosophy",
  "Physics",
  "Political Science",
  "Psychoanalytic Studies",
  "Psychology",
  "Religious Studies",
  "Russian & East European Studies",
  "Russian Language, Literature & Culture",
  "Science, Technology & Society",
  "Sociology",
  "South Asia Studies",
  "Statistics & Data Science",
  "Survey Research & Data Analytics",
  "Sustainability & Environmental Management",
  "Theatre Arts",
  "Urban Education",
  "Urban Real Estate & Development",
  "Urban Studies",
  "Yiddish",
]

export const COURSES: Record<string, { name: string; courses: string[] }> = {}
export const CLUBS: string[] = []
export const GREEK_LIFE: string[] = []
export const RESIDENCE_HALLS: { value: string; label: string; group?: string }[] = []
