export const MAJORS: string[] = [
  "African Studies",
  "American Studies",
  "Anthropology",
  "Applied Mathematics",
  "Applied Physics",
  "Archaeological Studies",
  "Architecture",
  "Art",
  "Astronomy",
  "Astrophysics",
  "Biomedical Engineering",
  "Black Studies",
  "Chemical Engineering",
  "Chemistry",
  "Classical Civilization",
  "Classics",
  "Cognitive Science",
  "Comparative Literature",
  "Computer Science",
  "Computer Science and Economics",
  "Computer Science and Mathematics",
  "Computer Science and Psychology",
  "Computing and Linguistics",
  "Computing and the Arts",
  "Earth and Planetary Sciences",
  "East Asian Languages and Literatures",
  "East Asian Studies",
  "Ecology and Evolutionary Biology",
  "Economics",
  "Economics and Mathematics",
  "Electrical Engineering",
  "Electrical Engineering and Computer Science",
  "Engineering Sciences (Chemical)",
  "Engineering Sciences (Electrical)",
  "Engineering Sciences (Environmental)",
  "Engineering Sciences (Mechanical)",
  "English",
  "Environmental Engineering",
  "Environmental Studies",
  "Ethics, Politics, and Economics",
  "Ethnicity, Race, and Migration",
  "Film and Media Studies",
  "French",
  "German Studies",
  "Global Affairs",
  "Greek, Ancient and Modern",
  "History",
  "History of Art",
  "History of Science, Medicine, and Public Health",
  "Humanities",
  "Italian Studies",
  "Jewish Studies",
  "Latin American Studies",
  "Linguistics",
  "Mathematics",
  "Mathematics and Philosophy",
  "Mathematics and Physics",
  "Mechanical Engineering",
  "Modern Middle East Studies",
  "Molecular Biophysics and Biochemistry",
  "Molecular, Cellular, and Developmental Biology",
  "Music",
  "Near Eastern Languages and Civilizations",
  "Neuroscience",
  "Philosophy",
  "Physics",
  "Physics and Geosciences",
  "Physics and Philosophy",
  "Political Science",
  "Portuguese",
  "Psychology",
  "Religious Studies",
  "Russian",
  "Russian, East European, and Eurasian Studies",
  "Sociology",
  "South Asian Studies",
  "Spanish",
  "Special Divisional Major",
  "Statistics and Data Science",
  "Theater, Dance, and Performance Studies",
  "Urban Studies",
  "Women's, Gender, and Sexuality Studies",
]

export const MINORS: string[] = [
  "African Studies",
  "American Studies",
  "Applied Mathematics",
  "Archaeological Studies",
  "Architecture",
  "Astronomy",
  "Biomedical Engineering",
  "Black Studies",
  "Chemical Engineering",
  "Classical Civilization",
  "Cognitive Science",
  "Computer Science",
  "East Asian Studies",
  "Education Studies",
  "Energy Studies",
  "English",
  "Environmental Studies",
  "Ethics, Politics, and Economics",
  "Ethnicity, Race, and Migration",
  "Film and Media Studies",
  "French",
  "German Studies",
  "Global Affairs",
  "Global Health Studies",
  "History",
  "History of Art",
  "History of Science, Medicine, and Public Health",
  "Human Rights Studies",
  "Italian Studies",
  "Jewish Studies",
  "Latin American Studies",
  "Linguistics",
  "Mathematics",
  "Modern Middle East Studies",
  "Music",
  "Near Eastern Languages and Civilizations",
  "Philosophy",
  "Political Science",
  "Portuguese",
  "Psychology",
  "Religious Studies",
  "Russian, East European, and Eurasian Studies",
  "Sociology",
  "South Asian Studies",
  "Spanish",
  "Statistics and Data Science",
  "Study of the City",
  "Theater, Dance, and Performance Studies",
  "Women's, Gender, and Sexuality Studies",
]

export const COURSES: Record<string, { name: string; courses: string[] }> = {}
export const CLUBS: string[] = []
export const GREEK_LIFE: string[] = []
export const RESIDENCE_HALLS: { value: string; label: string; group?: string }[] = []
